### ISSUE TITLE
Camera-to-arm coordinate conversion should be in a helper method

### ISSUE THREAD

**Issue by apflanag** [BMS-GM/pick-point#31]
The conversion between camera and arm coordinates is currently done directly in the main loop. Since this conversion may need to be done in different parts of the code in the future, moving it to a helper method would avoid copy-and-pasted code.

https://github.com/BMS-GM/pick-point/blob/d3ce4c31be6b9fa2f7c2d712d72ff49472192911/main.py#L251-L253

**Comment by TheOneJohiah** [comment]
May have a working helper method on my personal branch. Would like to test during team meeting
